### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by srnorsworthy** [mayankk2308/kryptonite#35] opened 2022-10-30 22:59 UTC
### What Mac are you using?

Mac Pro 2013

### What version of macOS are you using?

Newer

### Are you using OpenCore Legacy Patcher?

Yes

### What is your issue?

Running Ventura on this mac using OpenCore Patcher, and it runs fine. However, Kryptonite logs indicate that Kryptonite will not run.
------------
155:746 00:042 AAPL: ***********************************************************
155:790 00:043 AAPL: This version of Mac OS X is not supported on this platform!
155:834 00:043 AAPL: ***********************************************************
166:739 00:043 OC: Boot failed - Aborted
166:787 00:048 OCB: StartImage failed - Aborted
166:831 00:044 OCSB: Reenabling secure boot after Apple images

### Upload Kryptonite Logs

Click here, then drag and drop your files in this area.
[opencore-2022-10-30-193528.txt](https://github.com/mayankk2308/kryptonite/files/9897009/opencore-2022-10-30-193528.txt)

### Confirmation

- [X] I have uploaded the OpenCore **config.plist**.
- [X] I have uploaded all OpenCore Logs.
- [X] I have uploaded Lilu logs.
- [X] I have explained my issue in detail.

**Comment by srnorsworthy** [comment] 2022-10-31 02:43
The alternative would be for me to use purge-wrangler, but when I tried that, even with SIP disabled, it still found SIP needed to be disabled, so that didn't work, either. I clearly need help.

**Comment by srnorsworthy** [comment] 2022-10-31 04:20
One more observation: I had to Zap the PRAM on restart Cmd-Opt-P-R and get the 'chime' in order to restart, otherwise it would not restart at all.

**Comment by mayankk2308** [comment] 2022-11-06 17:16
AVX2 code cannot execute on older macs as is. Work for that is out of scope for this solution, which was originally intended for appropriately supported macOS version + hardware. OCLP support is not guaranteed. Rest is duplicate of https://github.com/mayankk2308/kryptonite/issues/34

**Closed by mayankk2308** 2022-11-06 17:16 UTC
