### ISSUE TITLE
Kernel panic, boot loop after disconnecting eGPU

### ISSUE THREAD

**Issue by JMY1000** [mayankk2308/kryptonite#12] opened 2021-08-08 05:46 UTC
# Problem Description

After installing Kryptonite, I’m able to successfully boot and connect to an eGPU, with display output. However, when I attempt to disconnect the eGPU using the menu bar item, the computer panics, hard locks, and shuts down automatically.

After this point, I’m able to load OpenCore and select a volume in the Kryptonite boot picker, but attempting to boot using Kryptonite results in the boot sequence stalling partway through before eventually it hard restarts itself. I’m still able to boot normally without OpenCore, but a reinstall of Kryptonite is required before I can boot again with it.

### Caveats and Details

- The 290X managed to disconnect successfully once, but only once. I have not been able to reproduce this.
- A few times the system[s] soft locked shortly after attaching the eGPU. I have not been able to reproduce this.
- Once the system hard locked and reset before I attempted to disconnect the eGPU.
- Unplugging the GPU without attempting to disconnect it safely appears to result in the same behavior.
- Both GPUs are detected but do not function or display detailed information without Kryptonite.
- Neither GPU is detected with purge-wrangler, although the enclosure is detected and turns on.

# System

### Laptops

- MacBookPro16,1 with macOS 10.15.4
- MacBookAir8,2 with macOS 10.14.6 and 10.15.4

### eGPU

- Razer Core X with R9 7870 and R9 290X

The R9 7870 has been verified as macOS compatible in a MacPro5,1, and with OpenCore in another machine (no additional boot flags were required for proper functionality). The R9 290X has been verified as functional. Both cards output proper displays when connected to the laptops.

# Logs

[Attached.](https://github.com/mayankk2308/kryptonite/files/6950286/Logs.zip) I can generate more if desired.

# Screenshots

None, sorry.

**Comment by Piipperi** [comment] 2021-08-11 08:51
Meanwhile, we're waiting for the dev to respond, I couldn't get my R9 280 to work on purge-wrangler neither.

This is because R9s are considered "legacy" GPUs and require further patching to get to work on macOS as an eGPU I think.

**Comment by JMY1000** [comment] 2021-08-11 18:47
> This is because R9s are considered "legacy" GPUs and require further patching to get to work on macOS as an eGPU I think.

I never had issues with purge-wrangler and my R9 Fury once the appropriate kext was installed.

I know compatibility is not guaranteed, but it seems strange that a card would work just fine in one Mac and not another.

**Comment by mayankk2308** [comment] 2021-09-07 03:25
Really appreciate the organized logs, thank you.

I've seen other people have eGPU disconnection issues as well, but this also occurs on natively supported systems (Thunderbolt 3 Macs, newer AMD GPUs) so this could be a macOS issue. I have newer GPUs (Vega, Navi) on TB3 Macs and they sometimes crash too.

If you could add `keepsyms=1` to your OpenCore boot-args and then reproduce the panic on your TB3 MBP and then share the panic logs, that'd be great. But looking at it as is, the failure is in Apple/AMD code and not due to Kryptonite.

**Comment by JMY1000** [comment] 2021-09-07 08:03
Thanks for the information; a bit disappointing given the current GPU market, but good to know nonetheless. I'm still a little confused as to why behavior would be so different (consistently) between the Fury and the 7870/290X, but I'll chalk that up to the driver. Also still not sure why reinstalling Kryptonite seems to be required after the panic ¯\\\_(ツ)_/¯

Attached are the logs with the `keepsyms=1` arg with the R9 7870 and MacBookPro16,1. I was going to try 10.15.7 as well, but unfortunately the update failed and I'm out of time. I'll see about trying Big Sur too, but it'll unfortunately have to wait a few weeks at an absolute minimum for me.

[logs.zip](https://github.com/mayankk2308/kryptonite/files/7119931/logs.zip)

**Comment by mayankk2308** [comment] 2021-09-08 06:48
Per logs, when system calls `IOService::stop` for the AMD GPU, that routine seems to fail. Probably an artifact with the drivers.

> Also still not sure why reinstalling Kryptonite seems to be required after the panic ¯\_(ツ)_/¯

I think I remember seeing something like this. The kernel panic message on boot seems to break OpenCore (perhaps there's some configuration I need to look into). The fix is to dismiss the KP by booting normally, after which booting via OpenCore again should work.

Closing this as unfortunately I don't have a solution and it seems to be an inherent driver issue.

**Closed by mayankk2308** 2021-09-08 06:48 UTC
