### ISSUE TITLE
mac mini 2014 with monterrey 12.3.1 the skip OpenCore Boot Picker not working

### ISSUE THREAD

**Issue by h2jose** [mayankk2308/kryptonite#27] opened 2022-04-24 05:48 UTC
### What Mac are you using?

Mac mini 7,1 (2014)

### What version of macOS are you using?

12.x

### Are you using OpenCore Legacy Patcher?

No

### What is your issue?

 i am using mac mini 2014, Monterrey 12.3.1, i use 2 monitors, prior i was using wrangler. i removed wrangler, installed kryptonite, picker and timeout in 0 into plist file. But only startup fine if i have connected a monitor to hdmi from mac mini. if i connect the 2 monitors to gpu, don't works. With wrangler i have not this problem.

### Upload Kryptonite Logs

Click here, then drag and drop your files in this area.

### Confirmation

- [X] I have uploaded the OpenCore **config.plist**.
- [X] I have uploaded all OpenCore Logs.
- [X] I have uploaded Lilu logs.
- [X] I have explained my issue in detail.

**Comment by mayankk2308** [comment] 2022-06-27 01:40
I believe the root cause of this issue is same as: https://github.com/mayankk2308/kryptonite/issues/9

I will close this as duplicate. 

Seems like for now you will need something like a dummy adapter to keep internal video output of your Mac enabled for it to boot properly with OpenCore.

**Closed by mayankk2308** 2022-06-27 01:40 UTC
