### ISSUE TITLE
[BUG] eGPU not working when plugged in during boot

### ISSUE THREAD

**Issue by jipvankuijk** [mayankk2308/kryptonite#33] opened 2022-10-10 16:11 UTC
### What Mac are you using?

MacPro6,1 (Late 2013)

### What version of macOS are you using?

12.x

### Are you using OpenCore Legacy Patcher?

No

### What is your issue?

When the eGPU is plugged in when the Mac is off, and I start the Mac with the eGPU already plugged in it won't work. It only works when I plug it in once the Mac sits on the login screen. This makes turning the Mac off and on again cumbersome. 

### Upload Kryptonite Logs

Click here, then drag and drop your files in this area.
[config.plist.zip](https://github.com/mayankk2308/kryptonite/files/9747467/config.plist.zip)

### Confirmation

- [X] I have uploaded the OpenCore **config.plist**.
- [X] I have uploaded all OpenCore Logs.
- [X] I have uploaded Lilu logs.
- [X] I have explained my issue in detail.

**Comment by jipvankuijk** [comment] 2022-10-10 16:13
Anyway thanks for the work so far, but would be nice to know if this plugged in during boot in a known bug or expected behaviour etc. And if anything can be done about it :D

**Comment by Piipperi** [comment] 2022-10-10 16:43
Do you have a display connected directly to the Mac Pro or just to the eGPU?

Wondering if this is related to my issue that's unfixable due to how OpenCore and Lilu works

**Comment by Piipperi** [comment] 2022-10-10 17:03
> Hey there, @Piipperi.
> 
> 
> 
> I have the BlackMagic Radeon 580 eGPU, I have the 5K monitor plugged in to the eGPU via Thunderbolt 3 cable. It only works after plugging in the eGPU to the MacPro after the Mac has fully booted. If its plugged in already during boot it shows no picture. 

So I'm guessing that means you only have one display, and nothing directly plugged into the Mac Pro.

- I think this could be related to the issue I'm having, however, my Mac will not boot into macOS properly at all if Lilu can't load properly (and Lilu is at the core of this issue likely, as it has a bug where if you start your computer without a display, it won't "fire" properly. This leads my system to not load drivers for things such as my Wi-Fi card at boot)

**Comment by jipvankuijk** [comment] 2022-10-10 17:06
@Piipperi I have an HDMI headless adapter I used to use with Mac Mini to get good resolution for headless VNC connections. I could try that some time, to see if that makes a difference. But it would still be annoying, but it could pin point the issue.

**Comment by Piipperi** [comment] 2022-10-10 17:11
> @Piipperi I have an HDMI headless adapter I used to use with Mac Mini to get good resolution for headless VNC connections. I could try that some time, to see if that makes a difference. But it would still be annoying, but it could pin point the issue. 

Yeah, I have to open my laptop's display each time I try to boot, I suggest you give the HDMI plug a try - however keep in mind that macOS does not let you disable monitors like Windows does, unless you use software like SwitchResX. So keeping a HDMI plug in all the time might be annoying.

**Comment by coex177** [comment] 2022-10-18 02:52
@jipvankuijk This weekend I was trying to get Windows installed with the eGPU and one of the threads I was reading said that the thunderbolt cable needed to be plugged into one of the bottom 2 ports. I did this and discovered that after using one of these 2 ports, the Mac boots when the eGPU is plugged in. Try doing this and see if it also fixes the issue for you.

**Comment by jipvankuijk** [comment] 2022-10-18 17:27
> 

I do get the bong sound but I don't get any picture, unplugging and replugging the egpu does not work. It has to only be plugged in after its done booting. Probably the loading bar but since I don't have a way of seeing that I wait until I'm sure its at the login window.

**Comment by coex177** [comment] 2022-10-18 17:53
If you are only plugging the eGPU in and no other monitor in any other port, I believe that you will not see an image until the login screen. I think this is a limitation of the OS, I'm not sure...I think I had read that somewhere. I have a second display connected directly to the Mac and it shows the loading boot screen after the bong sound on it, with nothing showing on the eGPU display until the login screen comes up.

**Comment by mayankk2308** [comment] 2022-11-06 17:23
If FileVault is enabled, then a direct connection to the Mac is needed to see the login UI. Same with the OC boot picker. To see it, a direct connection is needed (unless it has been manually disabled). The second issue is when FileVault isn’t enabled but Lilu kext is unable to launch without main display (directly connected to Mac). Finally, the third issue with 2013 Mac Pro can be a POST issue (no boot chime, stuck) when egpu is not plugged into bottom two ports during startup (this is a well known issue on egpu.io). Lilu not firing is duplicate of https://github.com/mayankk2308/kryptonite/issues/9. Closing. Please move further discussion there. The rest is unfortunately the current state of things and expected behavior.

**Closed by mayankk2308** 2022-11-06 17:23 UTC
